export {
    // ST re-exports
    // Native exports
    // HTML exports
};

// * MARK:Types Definitions

/**
 * @typedef {Object} ExtensionNameInterface
 * @property {(...mess: any[]) => void} log
 * @property {(...mess: any[]) => void} debug
 * @property {(...mess: any[]) => void} error
 */

/**
 * @typedef {Object} ExtensionSettings
 * @property {boolean} enabled
 * @property {boolean} debug
 */

// * MARK:Extension variables

const context = () => SillyTavern.getContext();

const {
    t,
    saveChat,
    substituteParams,
    setExtensionPrompt,
    scrollChatToBottom,
    callGenericPopup,
    getThumbnailUrl,
    Popup,
    POPUP_TYPE,
    extensionSettings: extension_settings,
    saveSettingsDebounced,
    powerUserSettings,
    eventSource,
    eventTypes
} = context();

const {
    lodash
} = SillyTavern.libs;

/**
 * @readonly
 * @enum {number}
 */
const debounceTimeout = Object.freeze({
    MICRO: 50,
    SHORT: 300,
    MED: 500,
    LONG: 700
});

const extensionName = "Extension-Template";
const extensionFullName = 'SillyTavern-Extension-Template';
const metadataName = extensionName.toLowerCase().replaceAll('-', '_');
const htmlSuffix = extensionName.toLowerCase();
const extensionFolderPath = `scripts/extensions/third-party/${extensionFullName}`;

/** @type {ExtensionSettings} */
const extensionSettings = extension_settings[extensionName];

/** @type {ExtensionSettings} */
const defaultSettings = {
    enabled: true,
    debug: false
};

const HTML_TEMPLATES = {
	/**
     * @typedef {Object} HTMLTemplateGetOptions
     * @property {boolean} [clone]
     *
     * @param {string} [fileName]
     * @param {HTMLTemplateGetOptions} [options]
     * @returns {Promise<JQuery<HTMLElement>>}
     */
    get: async function(fileName = 'settings', {clone = false} = {}) {
		if (!HTML_TEMPLATES[fileName]) {
            await $.get(`${extensionFolderPath}/source/templates/${fileName}.html`)
                .done(function(response) {
                    HTML_TEMPLATES[fileName] = $(response);
                })
                .fail(function(jqXHR, textStatus, errorThrown) {
                    ExtensionName.error({jqXHR, textStatus, errorThrown});
                });
        }

        const $file = HTML_TEMPLATES[fileName];

        if (!$file) {
            toastr.warning(t`HTML template could not be loaded`, extensionName);
            return $();
        }

		return clone ?
            $file.clone() :
            $file;
    }
};

// * MARK:Debugs methods

function log(...mess) {
    if (!extensionSettings.enabled || !extensionSettings.debug) return;

    console.log(`[${extensionName}]`, ...mess);
};

function debug(...mess) {
    if (!extensionSettings.enabled || !extensionSettings.debug) return;

    console.debug(`[${extensionName}]`, ...mess);
};

function error(...mess) {
    if (!extensionSettings.enabled || !extensionSettings.debug) return;

    console.error(`[${extensionName}]`, ...mess);
};

// * MARK:Extension methods

/**
 * Creates or populates elements
 * @param {string|HTMLElement} elem
 * @param {{class?:string; attr?:Object; data?:Object; innerHTML?: string; innerText?: string; append?: HTMLElement[]}} [options]
 */
function createElement(elem, options = {}) {
    // * Anything complex generated by this function should eventually be turned into an HTML template

    const element = typeof elem === 'string' ? document.createElement(elem) : elem;

    for (const [attr, value] of Object.entries(options.attr ?? {})) {
        element.setAttribute(attr, value);
    }

    for (const [key, value] of Object.entries(options.data ?? {})) {
        element.dataset[key] = value;
    }

    const classes = options.class ?? '';

    if (classes.length > 0)
        element.classList.add(...(classes.split(' ')));

    if (options.innerHTML) element.innerHTML = options.innerHTML ?? '';
    if (options.innerText) element.innerText = options.innerText ?? '';
    if (options.append) element.append(...(options.append ?? []));

    return element;
}

/**
 * @param {string?} [extraSuffix]
 * @returns {string} UUID
 */
function generateUUID(extraSuffix) {
    const randUUID = self?.crypto?.randomUUID();
    const uuid = !randUUID ? new Date().valueOf().toString() : randUUID.replaceAll('-', '_');

    return `${extraSuffix ?? metadataName}_${uuid}`;
}

/**
 * @returns {boolean}
 */
function isChatOpen() {
    const { chatId } = context();

    return !chatId ? false : true;
}

/**
 * @param {string|boolean|number} value
 * @param {'string'|'boolean'|'number'|string?} [force]
 * @returns {string|boolean|number}
 */
function parseValue(value, force) {
    const allowed = ['string', 'boolean', 'number'];

    if (!allowed.includes(typeof value)) return value;

    if (force === 'string') return String(value);
    if (force === 'number') return Number(value);
    if (force === 'boolean') return value === 'true';

    if (value === 'true' || value === 'false')
        return value === 'true';

    const number = Number(value);

    if (!isNaN(number)) return number;

    return String(value);
}

/**
 * MARK:Interface
 * @type {ExtensionNameInterface}
 */
globalThis.ExtensionName = {
    log,
    debug,
    error
};

// * MARK:Extension Settings

const settingsCallbacks = {
    /**	Triggers on enabled setting change. */
    enabled: () => {
        // Nothing by the moment
    }
}

/** Changes a setting value and triggers a callback if there's any on settingsCallbacks. */
function settingsBooleanButton(event) {
    const target = event.target;
    const value = Boolean($(target).prop('checked'));
    const setting = target.getAttribute(`${htmlSuffix}-setting`);
    const callback = settingsCallbacks[setting];

    extensionSettings[setting] = value;

    if (callback) callback();

    log('toggleSetting ' + setting, value);
    saveSettingsDebounced();
}

/** Changes a string setting value and triggers a callback if there's any on settingsCallbacks. */
function settingsTextButton(event) {
    const target = event.target;
    const value = String($(target).val());

    const setting = target.getAttribute(`${htmlSuffix}-setting`);
    const callback = settingsCallbacks[setting];

    extensionSettings[setting] = value;

    if (callback) callback();

    log('toggleSetting ' + setting, value);
    saveSettingsDebounced();
}

/** Changes a number setting value and triggers a callback if there's any on settingsCallbacks. */
function settingsNumberButton(event) {
    const target = /** @type {HTMLInputElement} */ (event.target);
    const raw_value = isNaN(target.valueAsNumber) ? 0 : target.valueAsNumber;
    const insideMinBoundary = (target.min !== '') ? (Number(target.min) <= raw_value) : true;
    const insideMaxBoundary = (target.max !== '') ? (Number(target.max) >= raw_value) : true;

    let value = raw_value;

    if (!insideMinBoundary) value = Number(target.min);
    if (!insideMaxBoundary) value = Number(target.max);

    const setting = target.getAttribute(`${htmlSuffix}-setting`);
    const callback = settingsCallbacks[setting];

    extensionSettings[setting] = value;

    if (callback) callback();

    log('toggleSetting ' + setting, value);
    saveSettingsDebounced();
}

/**	Logs setting's values. */
function displaySettings() {
    debug(`The extension is ${extensionSettings.enabled ? 'enabled' : 'disabled'}`);

    debug(`Debug mode is ${extensionSettings.debug ? 'active' : 'not active'}`);
    debug(structuredClone(extensionSettings));
}

/** Append settings menu on ST and set listeners. */
async function loadSettingsMenu() {
    const settingsHtml = await HTML_TEMPLATES.get('settings');

    // extensions_settings2 is an alternative
    $('#extensions_settings').append(settingsHtml);

    $(`#${htmlSuffix}-enabled`).on('input', settingsBooleanButton);
    $(`#${htmlSuffix}-debug`).on('input', settingsBooleanButton);
    $(`#${htmlSuffix}-check-configuration`).on('click', displaySettings);

    log('Settings menu created');

    $(`#${htmlSuffix}-enabled`).prop('checked', extensionSettings.enabled).trigger('input');
    $(`#${htmlSuffix}-debug`).prop('checked', extensionSettings.debug).trigger('input');

    log('Settings values initialized', extensionSettings);
}

/** Append settings menu on ST and set listeners. */
async function loadHTMLSettings() {
    const settingsHtml = await $.get(`${extensionFolderPath}/settings.html`);

    $("#extensions_settings").append(settingsHtml);

    // Event Listeners for the extension HTML
    $("#EXTENSION_NAME-activate-extension").on("input", settingsBooleanButton);
    $("#EXTENSION_NAME-activate-debug").on("input", settingsBooleanButton);
    $("#EXTENSION_NAME-check-configuration").on("click", displaySettings);

    log("loadHTMLSettings");
}

/** Init setting values on the menu */
function setSettings() {
    $("#EXTENSION_NAME-activate-extension").prop("checked", extensionSettings.enabled).trigger("input");
    $("#EXTENSION_NAME-activate-debug").prop("checked", extensionSettings.debug).trigger("input");

    log("setSettings", extensionSettings);
}

// * MARK:Initialize Extension

eventSource.once(eventTypes.APP_INITIALIZED, async function() {
    if (!context().extensionSettings[extensionName]) {
        context().extensionSettings[extensionName] = structuredClone(defaultSettings);
    }

    for (const key of Object.keys(defaultSettings)) {
        if (context().extensionSettings[extensionName][key] === undefined) {
            context().extensionSettings[extensionName][key] = defaultSettings[key];
        }
    }

    await loadSettingsMenu();
});
